[project]
name = "speechometer"
version = "0.0.1"
license-files = ["LICENSE", "LICENSES/*.txt", "NOTICE"]
dependencies = [
    "librosa",
    "numpy",
    "onnxruntime",
    "speechbrain @ git+https://github.com/speechbrain/speechbrain.git@develop",
    "torch",
    "torchaudio",
    "torchmetrics[audio]",
    "transformers",
]

[tool.black]
line-length = 80

[tool.setuptools]
package-dir = {"" = "src"}

[tool.setuptools.packages.find]
where = ["src"]
include = ["speechometer*"]

[tool.setuptools.package-data]
"speechometer.metrics" = ["*.onnx"]
